version: "3.9"

services:

  api-hello-world-port1:
    image: api-hello-world-port
    ports:
      - 8080:8080
    environment:
      PORT: 8080
  
  api-hello-world-port2:
    image: api-hello-world-port
    ports:
      - 8081:8081
    environment:
      PORT: 8081
  
  api-hello-world-port3:
    image: api-hello-world-port
    ports:
      - 8082:8082
    environment:
      PORT: 8082

  nginx:
    image: nginx
    volumes:
      - C:\FinalSistemasDistribuidos\nginx\default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "91:91"