server:
  port: 9090

servers:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8080,
                   localhost:8081,
                   localhost:8082
    ServerListRefreshInterval: 15000